apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: react-reload
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
# Profile for production
profiles:
  - name: prod
    build:
      artifacts:
      - image: react-reload
        context: app
      tagPolicy:
        customTemplate:
          template: prod
